### ISSUE TITLE
[Tracking] Chapters and sections

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/book#1]
- [ ] Introduction
- [ ] Getting Started
    - [ ] Installation
    - [ ] First steps with alloy
    - [ ] Common terminology
- [ ] Tutorials
    - [ ] Best practices
    - [ ] Transferring ETH
    - [ ] Listening to the mempool
    - [ ] Using flashbots
    - [ ] Tracing a transaction
    - [ ] Fetching the gas price in USD
    - [ ] Examples repo
- [ ] Migrating from Ethers
    - [ ] Helper traits for conversions
    - [ ] Where are all my types? (Diagram showing the equivalence of every alloy crate for each ethers crate)
    - [ ] Going from Ethers primitive types to Alloy primitive types
    - [ ] Going from using ethers to using alloy to decode data
        - [ ] Using alloy-sol-macro for static data
        - [ ] Using alloy-dyn-abi for dynamic data
        - [ ] Parsing ABIs (alloy-json-abi)
        - [ ] When should I use each?
    - [ ] Going from Ethers Providers to Alloy Providers
        - [ ] Ethers's Middleware vs Alloy Fillers
        - [ ] A gentle introduction to Alloy's use of Tower
        - [ ] The RPC types
        - [ ] Understanding the power of Alloy Contract
        - [ ] Queries and subscriptions
        - [ ] Sending transactions
    - [ ] Going from Ethers Signers to Alloy Signers
    - [ ] Going from Ethers Genesis to Alloy Genesis
- [ ] Building with Alloy
    - [ ] Basic building blocks
        - [ ] Using big numbers
        - [ ] Basic hash & address types
        - [ ] Common conversions
        - [ ] Creating instances
        - [ ] Comparisons and equivalence
    - [ ] Connecting to a blockchain
        - [ ] Setting up a Provider
        - [ ] Available transports
            - [ ] HTTP
            - [ ] WS
            - [ ] IPC
        - [ ] Understanding fillers
        - [ ] The `Network` abstraction
        - [ ] Queries
        - [ ] Transactions
            - [ ] Using the transaction builder
            - [ ] Sending a legacy TX
            - [ ] Sending an EIP-1559 TX
            - [ ] Using access lists
            - [ ] Sending an EIP-4844 TX
            - [ ] Awaiting for receipts
        - [ ] Best practices
    - [ ] Interacting with contracts
        - [ ] Initializing a contract instance
        - [ ] Encoding & decoding data
            - [ ] Best practices when using the static and dynamic encoder
        - [ ] Listening to events
        - [ ] Querying historic events
        - [ ] Watching blocks
        - [ ] Setting up multiple subscriptions
    - [ ] Using signers
        - [ ] Creating a wallet
        - [ ] Using a hardware wallet
            - [ ] Ledger
            - [ ] Trezor
        - [ ] Using a mnemonic
        - [ ] Using a keystore
        - [ ] Using a raw private key
        - [ ] Signing messages
        - [ ] Permit hashes
    - [ ] Using Anvil
        - [ ] Booting up Anvil
        - [ ] Deploying Contracts
        - [ ] Forking
 - [ ] Appendix
    - [ ] FAQ
    - [ ] Help us improve Alloy

**Comment by zerosnacks** [comment]
From feedback:

The intended api is pretty highlevel (implemented as articles in `highlights`)

- sol!
- TransactionRequest
- ProviderBuilder
  - with_recommended_fillers
- Provider
  - particularly &dyn Provider<T>
  
We can then drill down into specific guide for advanced things like: 
- "add a transport layer with tower"
- "add a provider layer"

And guides for
- "implement a transport"
- "implement a network"
- "implement a provider"
- "implement a providerlayer"

**Comment by zerosnacks** [comment]
As a highlight page: Transaction lifecyle 

A deep dive into how a transaction is constructed, signed and send. Also touches on `Filler` and layering.

Touches on CustomLayer / RetryLayer (https://github.com/alloy-rs/alloy/issues/717) cc @yash-atreya
