### ISSUE TITLE
[Tracking] Notes

### ISSUE THREAD

**Issue by zerosnacks** [alloy-rs/book#4]
## Missing features

- [x] missing `rpc-types-anvil` export from `alloy`
- [ ] ~~rename `json-rpc` to `rpc-json` for consistency~~
- [x] remove redundant `rpc` feature flag as a category
- [x] remove redundant `rpc-types` feature flag as a category

## Missing docs

- [ ] missing from `alloy` docs: eip7547
- [ ] missing from `alloy-core` docs: alloy-sol-macro-input

## Optimize

- [ ] Replace `mdbook-external-links` installation in Github workflow

## Questions

- [x] Are Ethers' `H256` and Alloys' `B256` interchangeable?
